shared:
  image: node:16
  steps:
    - echo: echo hi
jobs:
  job1:
    requires: [~commit]
  job2000:
    requires: [job1]
  job3:
    requires: [job1]
  job4:
    requires: [job2000, job3]
stages:
  starfish:
    jobs: [job1, job4]
    description: "starfish deploy jobs"
  seahorse:
    jobs: [job2000, job3]
    description: "seahorse deploy jobs"
    color: '#00FFFF'
