shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
  a:
    requires: []
  b:
    requires: [~a]
    steps:
    - echo: exit 1;
  c:
    requires: [~b]
  target:
    requires: [~stage@incomplete_fail]
stages:
  incomplete_fail:
    requires: [~hub]
    jobs: [a, b, c]
    description: First stage
    teardown:
      image: node:lts
      steps:
        - init: echo 'teardown'
