shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
  a:
    requires: []
  b:
    requires: [~a]
  c:
    requires: [~b]
  target:
    requires: [~stage@simple_success]
stages:
  simple_success:
    requires: [~hub]
    jobs: [a, b, c]
    description: First stage
