shared:
  image: node:16
  steps:
    - echo: echo hi
jobs:
  job10:
    requires: [~commit]
  job2:
    requires: [job10]
  job3:
    requires: [job10]
  job4:
    requires: [job2, job3]
stages:
  starfish:
    jobs: [job10, job4]
    description: "starfish deploy jobs"
  seahorse:
    jobs: [job2, job3]
    description: "seahorse deploy jobs"
    color: '#00FFFF'
