shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
  # a:
  #   requires: []
  # b:
  #   requires: [~a]
  c:
    requires: []
    steps:
    - echo: exit 1;
  target:
    requires: [~stage@simple_fail]
stages:
  simple_fail:
    requires: [~hub]
    jobs: [c]
    description: First stage
    teardown:
      image: node:lts
      steps:
        - init: echo 'teardown'
